name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-18.04]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libkrb5-dev

      - name: Install dependencies
        env:
          JOBS: 'max'
        run: |
          npm ci

      - name: Lint
        run: npm run lint

      - name: 'Capitalise binary (macOS only)'
        if: runner.os == 'macOS'
        run: |
          sed -i '.bak' 's/"executableName": "aeon"/"executableName": "Aeon"/' package.json

      - name: Compile
        run: npm run make

      - name: Test
        if: runner.os == 'Windows' || runner.os == 'macOS'
        run: npm run test

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: out/make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "out/make/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
